version: '3.9'

networks:
  tasks-network:
    driver: bridge

services:
  tasks-postgres:
    image: postgres:14.4
    container_name: tasks-postgres
    environment:
      - POSTGRES_DB=HiperiumCityTasksDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    networks:
      - tasks-network

  tasks-api:
    image: hiperium/hiperium-city-tasks-api:1.5.0-arm64
    container_name: tasks-api
    build:
      context: $PWD/src/hiperium-city-tasks-api
      dockerfile: $PWD/src/hiperium-city-tasks-api/Dockerfile
      args:
        - quarkus_profile=dev
    env_file:
      - ./utils/docker/compose/dev.env
    depends_on:
      - tasks-postgres
    ports:
      - "8080:8080"
    networks:
      - tasks-network

  tasks-pwa:
    image: hiperium/hiperium-city-tasks-pwa:1.5.0-arm64
    container_name: tasks-pwa
    build:
      context: $PWD/src/hiperium-city-tasks-pwa
      dockerfile: $PWD/src/hiperium-city-tasks-pwa/Dockerfile
    volumes:
      - ./utils/docker/compose/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - tasks-network
